### PR TITLE
Apple Silicon support

### PR DESCRIPTION
**Pull request by Tarik02**
Compile universal (x86_64 and arm64) binary for macOS.

### CODE REVIEW

**Comment by mellinoe** [comment]
Looks reasonable, I'll just need to test this on my x86-only Mac to make sure nothing has regressed. I don't have access to an arm64 Apple device at the moment.

**Comment by zaafar** [comment]
if Eric accepts https://github.com/mellinoe/ImGui.NET-nativebuild/pull/5
you may wanna do (or help me do) your MR in github actions.

**Comment by Tarik02** [comment]
@zaafar Of course. After he accepts it, I'll add commits here to adapt it for GitHub actions.

**Comment by zaafar** [comment]
it's time :)

**Comment by Tarcontar** [comment]
Verified on a M1 Macbook Air -> works fine! :)

**Comment by zaafar** [comment]
> This looks good to me

Unfortunately it’s not, it’s modifying Travis and this repo now uses github actions.

**Pull request merged**
